version: '3.9'
services:
  bilibili_tool:
    image: ghcr.io/raywangqvq/bilibili_tool_pro
    container_name: bili
    restart: unless-stopped
    tty: true
    volumes:
      - ./Logs:/app/Logs
      - ./appsettings.json:/app/appsettings.json
      - ./cookies.json:/app/cookies.json
    environment:
      # 定时任务
      - Ray_DailyTaskConfig__Cron=40 16 * * *
